services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGO_URI: ${MONGO_URI}

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "localhost:27017/qna", "--eval", "'db.runCommand({ ping: 1 }).ok'"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  mongo-data:
